import java.awt.event.ActionEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;

import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
public class HighScores extends javax.swing.JDialog{

    /**
     * Creates new form HighScores
     * @throws IOException 
     */
    public HighScores(java.awt.Frame parent, boolean modal) throws IOException {
        super(parent, modal);
        initComponents();
    }
    
    public void setLocalScores(Game thisGame){
    	LocalScoreLabel.setText("Your Score is: " + thisGame.Score);
    	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @throws IOException 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws IOException {

        scoreLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        closeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        LocalScoreLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        scoreLabel.setText("High Scores");
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }

			private void exitButtonActionPerformed(ActionEvent evt) {
				System.exit(ABORT);
				
			}
        });
        
        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }

			private void closeButtonActionPerformed(ActionEvent evt) {
				setVisible(false);
				
			}
        });
        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
 
        BufferedReader in = new BufferedReader(new FileReader("scores.dat"));
        String line = in.readLine();
        while(line != null){
          jTextArea1.append(line + "\n");
          line = in.readLine();
        }
        in.close();
        
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(scoreLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
              .addGroup(layout.createSequentialGroup()
                    	.addGap(100,100,100)
                    	.addComponent(LocalScoreLabel))
                    .addGroup(layout.createSequentialGroup()
                    	.addGap(100,100,100)
                    	.addComponent(closeButton))
                    .addGroup(layout.createSequentialGroup()
                    	.addGap(100,100,100)
                    	.addComponent(exitButton))
                    	.addGap(15,15,15)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(scoreLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                //.addGap(15,15,15)
                .addComponent(LocalScoreLabel)
                .addContainerGap(30, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(closeButton))
            //.addGroup(layout.createSequentialGroup()
                .addComponent(exitButton)//)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel LocalScoreLabel;
    // End of variables declaration//GEN-END:variables
}
